name: C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install compiller
        run: sudo apt-get install -y gcc g++
      - name: install flex and bison
        run: sudo apt install flex bison
      - name: install CMake
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz
          tar -zxvf cmake-3.15.2.tar.gz
          cd cmake-3.15.2
          ./bootstrap
          make
          sudo make install
          gcc --version
          cmake --version